apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: dapr-demo
  labels:
    app: demo-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app 
  template:
    metadata:
      labels:
        app: demo-app 
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: my-awesome-app
    spec:
      containers:
      - name: demo-app 
        image: nginx:1.14.2
        ports:
        - containerPort: 80
